### ISSUE TITLE
Restoring old soundtracks?

### ISSUE THREAD

**Issue by rafael-57** [ooa113y/umineko-catbox-english#14]
Sorry, I know this isn't strictly related to your patch and it's a base-game issue, but how hard would it be to replace the new songs with the old ones? 

Considering that it's only 4 tracks, would it be as simple as getting the old audio file and replacing it with the new one while keeping the new names?

Thank you for your amazing work!!

**Comment by ooa113y** [comment]
I have no intention of doing anything of this nature, it goes beyond (and, in large part, *against*) what this patch is supposed to do, which is to say, translate the game to English.

If you wanted to do it yourself, you'd need to first somehow convert the old songs to the Switch NXA audio format, as that's the only one the game supports. I know of no tool that is capable of creating this type of file, so unless you reverse-engineer the format and create a file converter yourself, you won't have much luck there. If you *really* want to try, you can start by looking at the code for [vgmstream](https://github.com/vgmstream/vgmstream), a library/app capable of playing various console-specific music formats, but I can't really provide help beyond that point.

However, if you do find/make a converter, then yes, you should be able to "just" place the converted files in the appropriate romfs folder before running the build process, after which you can build the patch following the instructions [here](https://github.com/ooa113y/umineko-catbox-english/blob/master/CONTRIBUTING.md#building).
